### PR TITLE
backport to 1.18.2

### LINKED ISSUE #8: 1.18 doesn't work
Releases of the mod say it works on 1.18.x and 1.19.x and so does `fabric.mod.json` but it just doesn't on 1.18.
I know the README says you won't backport so it'd just be nice if you could remove the apparent support for 1.18.
There's a backport of the dev branch for 1.18.2 on my fork (doesn't work on 1.19), just let me know if you want a PR for it.

### PR DESCRIPTION
**Pull request by arnokeesman**
this probably needs a separate branch, in my testing it stopped working for 1.19 (only tested .4)
#8

### CODE REVIEW

**Comment by Steveplays28** [comment]
Thanks! I'll take a look sometime this or next week.

**Comment by Steveplays28** [comment]
I'm going to finalize the new features in the `development` branch, and then I'll merge your backport. Thanks a bunch for the PR, looks good.

**Comment by arnokeesman** [comment]
All good, I've implemented restart warnings in chat and a different
disconnect message locally, will create some PRs for that as well if you're
interested

**Comment by Steveplays28** [comment]
That would be neat! Appreciate it.
Still need to implement a restart countdown so if you've got that ready that's great, and a custom disconnect message is nice as well!

**Comment by Steveplays28** [comment]
Thanks for the PR! Merged it.
I'm going to polish it up and release it sometime this weekend.

**Pull request merged**
