### PR TITLE
restart warns and disconnect message

### PR DESCRIPTION
**Pull request by arnokeesman**
This adds restart warnings which addresses some of #6, just without the placeholder.
Disconnects all players using `config.restartMessage`.
Also adds cloth-config to the mod dependencies.
If you feel like you need to squash some of the commit mess, feel free to do so.

### CODE REVIEW

**Comment by Steveplays28** [comment]
Thanks! I'll review it sometime this week, if I can. Just setting up a release GitHub action.

**Comment by arnokeesman** [comment]
Might have to add the minecraft version to the filenames

**Comment by Steveplays28** [comment]
That's a good idea and definitely something I want to start doing to avoid confusion.

**Review by Steveplays28 — APPROVED** [review]

**Comment by Steveplays28** [comment]
Thanks for the PR!

**Pull request merged**
